PROJECT = rest_hello_world
PROJECT_DESCRIPTION = Cowboy REST Hello World example
PROJECT_VERSION = 1

DEPS = cowboy
dep_cowboy = git https://github.com/ninenines/cowboy master

include ../../erlang.mk
