PROJECT = rest_basic_auth
PROJECT_DESCRIPTION = Cowboy Basic HTTP Authorization example
PROJECT_VERSION = 1

DEPS = cowboy
dep_cowboy = git https://github.com/ninenines/cowboy master

include ../../erlang.mk
