PROJECT = rest_stream_response
PROJECT_DESCRIPTION = Cowboy REST example with streaming
PROJECT_VERSION = 1

DEPS = cowboy
dep_cowboy = git https://github.com/ninenines/cowboy master

include ../../erlang.mk
