PROJECT = static_world
PROJECT_DESCRIPTION = Cowboy static file handler example
PROJECT_VERSION = 1

DEPS = cowboy
dep_cowboy = git https://github.com/ninenines/cowboy master

include ../../erlang.mk
