PROJECT = markdown_middleware
PROJECT_DESCRIPTION = Cowboy static file handler example with middleware component
PROJECT_VERSION = 1

DEPS = cowboy
dep_cowboy_commit = master

include ../../erlang.mk
