PROJECT = markdown_middleware
PROJECT_DESCRIPTION = Cowboy static file handler example with middleware component
PROJECT_VERSION = 1

DEPS = cowboy markdown
dep_cowboy_commit = master
dep_markdown = git https://github.com/hypernumbers/erlmarkdown master

REL_DEPS = relx

include ../../erlang.mk
