= Cowboy examples

* link:chunked_hello_world[]:
  demonstrate chunked data transfer with two one-second delays

* link:compress_response[]:
  send a response body compressed if the client supports it

* link:cookie[]:
  set cookies from server and client side

* link:echo_get[]:
  parse and echo a GET query string

* link:echo_post[]:
  parse and echo a POST parameter

* link:eventsource[]:
  eventsource emitter and consumer

* link:file_server[]:
  file server with directory listing

* link:hello_world[]:
  simplest example application

* link:markdown_middleware[]:
  static file handler with markdown preprocessor

* link:rest_basic_auth[]:
  basic HTTP authorization with REST

* link:rest_hello_world[]:
  return the data type that matches the request type (ex: html, text, json)

* link:rest_pastebin[]:
  create text objects and return the data type that matches the request type (html, text)

* link:ssl_hello_world[]:
  simplest SSL application

* link:upload[]:
  multipart/form-data upload

* link:websocket[]:
  websocket example

== Other languages

* https://github.com/joshrotenberg/elixir_cowboy_examples[Elixir]
* https://github.com/quasiquoting/lfe-cowboy-examples[LFE]
