PROJECT = web_server
PROJECT_DESCRIPTION = Cowboy static directory indexing example
PROJECT_VERSION = 1

DEPS = cowboy
dep_cowboy = git https://github.com/ninenines/cowboy master

include ../../erlang.mk
