PROJECT = compress_response
PROJECT_DESCRIPTION = Cowboy compressed response example
PROJECT_VERSION = 1

DEPS = cowboy
dep_cowboy = git https://github.com/ninenines/cowboy master

include ../../erlang.mk
