PROJECT = ssl_hello_world
PROJECT_DESCRIPTION = Cowboy SSL Hello World example
PROJECT_VERSION = 1

DEPS = cowboy
LOCAL_DEPS = ssl
dep_cowboy_commit = master

REL_DEPS = relx

include ../../erlang.mk
